-- 코드를 작성해주세요
# SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
# FROM DEVELOPERS A
# WHERE (SKILL_CODE & 256)>0
# OR
# (SKILL_CODE &1024)>0
# ORDER BY ID ASC
SELECT DISTINCT a.ID, a.EMAIL, a.FIRST_NAME, a.LAST_NAME
FROM DEVELOPERS a, SKILLCODES b
WHERE 
    (a.SKILL_CODE & b.CODE) > 0
    AND b.NAME IN ("Python", "C#")
ORDER BY a.ID;